M48
; DRILL file {KiCad (6.0.10)} date Thu Feb 23 17:52:51 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-23T17:52:51-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X6.3004Y-3.6665
X6.3985Y-3.7742
X6.4665Y-3.7019
T2
X6.3978Y-3.2915
X6.5978Y-3.2915
T0
M30
